# Generated by Django 3.0.2 on 2020-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
