# Generated by Django 3.0.2 on 2020-01-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('spider', '0002_auto_20200121_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='newsitem',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
